// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDarOowvPKCWP9_KrDk7ZK_r_9qUYbc1sU',
    appId: '1:617529080485:web:90d86d2dc7d848082e6b4c',
    messagingSenderId: '617529080485',
    projectId: 'urbannest-a43be',
    authDomain: 'urbannest-a43be.firebaseapp.com',
    databaseURL: 'https://urbannest-a43be-default-rtdb.firebaseio.com',
    storageBucket: 'urbannest-a43be.appspot.com',
    measurementId: 'G-C0TRWRPC6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBjY9G632nTNsIYa2uq_SUfDf-pT7S5fE',
    appId: '1:617529080485:android:c1b79b0333bc1f8a2e6b4c',
    messagingSenderId: '617529080485',
    projectId: 'urbannest-a43be',
    databaseURL: 'https://urbannest-a43be-default-rtdb.firebaseio.com',
    storageBucket: 'urbannest-a43be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjNZ0u7w3npgK4tjOcIB3mKzV8nk8A5Hs',
    appId: '1:617529080485:ios:6d94975cc55a9bcb2e6b4c',
    messagingSenderId: '617529080485',
    projectId: 'urbannest-a43be',
    databaseURL: 'https://urbannest-a43be-default-rtdb.firebaseio.com',
    storageBucket: 'urbannest-a43be.appspot.com',
    androidClientId: '617529080485-87t881f36aqsup3fihib848niio7a2mt.apps.googleusercontent.com',
    iosClientId: '617529080485-mpcsoe72bctrtc1jnn4n3qa429cn0n1m.apps.googleusercontent.com',
    iosBundleId: 'com.shelter.myghar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjNZ0u7w3npgK4tjOcIB3mKzV8nk8A5Hs',
    appId: '1:617529080485:ios:cbfec555051dede22e6b4c',
    messagingSenderId: '617529080485',
    projectId: 'urbannest-a43be',
    databaseURL: 'https://urbannest-a43be-default-rtdb.firebaseio.com',
    storageBucket: 'urbannest-a43be.appspot.com',
    androidClientId: '617529080485-87t881f36aqsup3fihib848niio7a2mt.apps.googleusercontent.com',
    iosClientId: '617529080485-roln2oapjaflkm4s2cs4m56buoqrr9m0.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbannests.RunnerTests',
  );
}
